"""add canonical entities

Revision ID: 4b2aac44e7e7
Revises: 
Create Date: 2026-09-02 16:10:38.597293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2aac44e7e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entities', sa.Column('canonical_entity_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'entities', 'canonical_entities', ['canonical_entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_column('entities', 'canonical_entity_id')
    op.drop_table('canonical_entities')
    # ### end Alembic commands ###
